// Builds src/www.generated.ts: the MuseBook page with its fonts inlined, so
// the app never needs the internet to show the book.
import fs from "node:fs";
const root = new URL("../", import.meta.url);
const fontsDir = new URL("www/fonts/", root);
let css = fs.readFileSync(new URL("fonts.css", fontsDir), "utf8");
css = css.replace(/url\((f\d+\.woff2)\)/g, (_, f) =>
  `url(data:font/woff2;base64,${fs.readFileSync(new URL(f, fontsDir)).toString("base64")})`);
let html = fs.readFileSync(new URL("www/musebook.html", root), "utf8");
if (!html.includes("/*FONTS*/")) throw new Error("font placeholder missing");
html = html.replace("/*FONTS*/", () => css);
// The looks: one stylesheet per look in www/looks, inlined in a fixed order.
if (!html.includes("/*LOOKS*/")) throw new Error("looks placeholder missing");
const looks = ["noir", "celestial"].map((n) => fs.readFileSync(new URL(`www/looks/${n}.css`, root), "utf8")).join("\n");
html = html.replace("/*LOOKS*/", () => looks);
// Textures (CC0, shrunk to small webp in www/tex) go inside the page so the
// looks work offline. Each one is written once as a CSS variable or class.
html = html.replace(/url\(tex\/([\w-]+\.webp)\)/g, (_, f) =>
  `url(data:image/webp;base64,${fs.readFileSync(new URL(`www/tex/${f}`, root)).toString("base64")})`);
if (!html.includes("<script>/*I18N*/</script>")) throw new Error("i18n placeholder missing");
const i18n = fs.readFileSync(new URL("www/i18n.js", root), "utf8");
html = html.replace("<script>/*I18N*/</script>", () => "<script>" + i18n + "</script>");
// The app pads around the page for the status and nav bars already, so the
// page's own safe-area padding would double it (a gap above the top bar).
html = html.replace(/env\(safe-area-inset-(top|bottom),0px\)/g, "0px");
if (/https?:\/\/fonts\./.test(html)) throw new Error("page still loads fonts from the internet");
fs.writeFileSync(new URL("src/www.generated.ts", root),
  "// Generated by scripts/build-www.mjs from www/musebook.html. Don't edit.\n" +
  `export const WWW_HTML = ${JSON.stringify(html)};\n`);
console.log("www.generated.ts:", (html.length / 1024).toFixed(0), "KB");
